$ python demo.py
training with dataset of 2 samples and validating with randomly splitted 1 samples
placeholder_dataset/subdirectory/example.wav None None {'ffmpeg': <class 'torchaudio._backend.ffmpeg.FFmpegBackend'>}
<class 'torchaudio._backend.ffmpeg.FFmpegBackend'>
placeholder_dataset/example2.wav None None {'ffmpeg': <class 'torchaudio._backend.ffmpeg.FFmpegBackend'>}
<class 'torchaudio._backend.ffmpeg.FFmpegBackend'>
/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/autograd/graph.py:744: UserWarning: Error detected in BmmBackward0. Traceback of forward call that caused the error:
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/vector_quantize_pytorch.py", line 470, in torch_dynamo_resume_in_forward_at_458
    dist = -cdist(flatten, embed)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/vector_quantize_pytorch.py", line 32, in cdist
    xy = einsum('b i d, b j d -> b i j', x, y) * -2
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:111.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "demo.py", line 139, in <module>
    trainer.train()
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/audiolm_pytorch/trainer.py", line 707, in train
    logs = self.train_step()
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/audiolm_pytorch/trainer.py", line 576, in train_step
    loss, (recon_loss, multi_spectral_recon_loss, adversarial_loss, feature_loss, all_commitment_loss) = self.soundstream(wave, return_loss_breakdown = True)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1530, in _wrapped_call_impl
    return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/audiolm_pytorch/soundstream.py", line 830, in forward
    x = self.encoder_attn(x)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/audiolm_pytorch/soundstream.py", line 837, in torch_dynamo_resume_in_forward_at_830
    x, indices, commit_loss = self.rq(x)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 296, in forward
    out = tuple(rvq(chunk, indices = chunk_indices, **forward_kwargs) for rvq, chunk, chunk_indices in zip_longest(self.rvqs, x, indices))
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 296, in torch_dynamo_resume_in_forward_at_296
    out = tuple(rvq(chunk, indices = chunk_indices, **forward_kwargs) for rvq, chunk, chunk_indices in zip_longest(self.rvqs, x, indices))
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 296, in <genexpr>
    out = tuple(rvq(chunk, indices = chunk_indices, **forward_kwargs) for rvq, chunk, chunk_indices in zip_longest(self.rvqs, x, indices))
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 153, in forward
    rand = random.Random(rand_quantize_dropout_fixed_seed) if exists(rand_quantize_dropout_fixed_seed) else random
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 155, in torch_dynamo_resume_in_forward_at_153
    rand_quantize_dropout_index = rand.randrange(self.quantize_dropout_cutoff_index, num_quant)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/residual_vq.py", line 177, in torch_dynamo_resume_in_forward_at_155
    quantized, *rest = layer(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/vector_quantize_pytorch.py", line 904, in forward
    quantize, embed_ind, distances = self._codebook(x, **codebook_forward_kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/vector_quantize_pytorch/vector_quantize_pytorch.py", line 458, in forward
    self.init_embed_(flatten, mask = mask)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 500, in transform
    tracer.run()
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2149, in run
    super().run()
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 810, in run
    and self.step()
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 484, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 548, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1001, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1178, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1251, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/output_graph.py", line 1232, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/__init__.py", line 1731, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/backends/common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 186, in aot_dispatch_autograd
    fx_g, joint_inputs, maybe_subclass_meta = aot_dispatch_autograd_graph(  # type: ignore[misc]
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 173, in aot_dispatch_autograd_graph
    fx_g = _create_graph(joint_fn_to_trace, updated_joint_inputs, aot_config=aot_config)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/dispatch_and_compile_graph.py", line 40, in _create_graph
    fx_g = make_fx(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 1081, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 541, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_dynamo/external_utils.py", line 36, in inner
    return fn(*args, **kwargs)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 793, in trace
    (self.create_arg(fn(*args)),),
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/fx/_symbolic_trace.py", line 652, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/fx/experimental/proxy_tensor.py", line 559, in wrapped
    out = f(*tensors)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 517, in joint_helper
    return _functionalized_f_helper(primals, tangents)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 383, in _functionalized_f_helper
    f_outs = fn(*f_args)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 251, in inner_fn_with_anomaly
    return inner_fn(*args)
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/_functorch/_aot_autograd/traced_function_transforms.py", line 236, in inner_fn
    backward_out = torch.autograd.grad(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/autograd/__init__.py", line 412, in grad
    result = _engine_run_backward(
  File "/home/rec/.conda/envs/fix-121334/lib/python3.8/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 512, 1024]] is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
